version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: app
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: album_database
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql"]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 5s
    restart: always
    networks:
      - alamoa-network

  web:
    image: web:latest
    container_name: web
    environment:
      MYSQL_USER: app
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: album_database
      MYSQL_HOST: mysql
    ports:
      - 8080:8080
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
    networks:
      - alamoa-network
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://web:8080/ping"]
      interval: 3s
      timeout: 5s
      retries: 5

networks:
  alamoa-network:
    driver: bridge
