openapi: 3.0.3
info:
  title: Go API Template
  version: 1.0.0
# servers:
#   - url: http://0.0.0.0:8080/api/v1
paths:
  /album:
    post:
      operationId: CreateAlbum
      summary: Create a new album
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AlbumCreateRequest"
        required: true
      responses:
        "204":
          description: No Content
  /album/{id}:
    get:
      operationId: GetAlbum
      summary: Find album by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AlbumGetResponse"
components:
  schemas:
    ID:
      type: integer
    Title:
      type: string
    AlbumCreateRequest:
      type: object
      properties:
        title:
          $ref: "#/components/schemas/Title"
      required:
        - title
    AlbumGetResponse:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/ID"
        title:
          $ref: "#/components/schemas/Title"
      required:
        - title
